- id: doi:10.1038/s41551-024-01277-5
  date: 2024-11-01
  tags:
    - CRISPR-Cas9
    - large deletion detection algorithm
- id: doi:10.3390/app132011399
  date: 2023-10-17
  tags:
    - RNA-seq analysis
    - network propagation
    - web-based tool
    - gene regulatroy network
    
- id: doi:10.1093/bioinformatics/btad582
  date: 2023-09-22
  tags:
    - gene-level biomarker discovery
    - multi-omics data
    - graph neural network
    
- id: doi:10.1038/s41467-022-30925-0
  date: 2022-6-7
  tags:
    - knowledge graphs
    - network analysis
- id: doi:10.1109/BigData52589.2021.9671953
  date: "2021-12-15"
  tags:
    - clustering

- id: doi:10.1093/bioinformatics/btz306
  date: 2021-7-12
  tags:
    - time-series analysis
    - miRNA-mRNA target prediction

- id: doi:10.3389/fgene.2021.652623
  date: 2021-5-10
  tags:
    - kernel canonical correlation analysis
    - gene regulatroy network
    
- id: doi:10.1093/bib/bbaa032
  date: "2021-01-01"
  tags:
    - machine learning
    - multi-omics integration
    
- id: doi:10.3389/fgene.2020.564792
  date: "2020-11-12"
  tags: 
    - deep learning
    - auto-encoder
    - tensor-decomposition
    - multi-omics integration
    - drug response prediction
    
- id: doi:10.1093/bioinformatics/bty275
  date: 2018-7-1
  tags:
    - convolutional neural network
    - deep learning
    - protein family prediction
    
- id: doi:10.1016/j.ymeth.2017.06.004
  date: 2017-7-15
  tags:
    - web-based tool
    - visualization
    - miRNA-mRNA target prediction
    
- id: doi:10.1371/journal.pone.0174999
  date: 2017-3-31
  tags:
    - web-based tool
    - miRNA-mRNA target prediction
    - literature mining
